version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run build
      - zip -qr code.zip dist node_modules ormconfig.js
      - aws cloudformation package --template-file cloudformation.yml --s3-bucket aws-cloudformation-package-cli --output-template-file packaged.yml

artifacts:
  files:
    - packaged.yml