version: 0.2

phases:
  build:
    commands:
      - docker-compose up --build --exit-code-from nest
      - npm install
      - npx serverless package
      - mv .serverless/eventlab-v2.zip code.zip
      - export HASH=`md5sum code.zip | awk '{print substr($1, 1, 20)}'`
      - sed -i -e "s|__VERSIONHASH__|$HASH|g" cloudformation.yml
      - cat cloudformation.yml
      - aws cloudformation package --template-file cloudformation.yml --s3-bucket aws-cloudformation-package-cli --output-template-file packaged.yml
artifacts:
  files:
    - packaged.yml