version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Docker HUB...
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf '[{"name":"CONTAINER_NAME","imageUri":"AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/IMAGE_REPO_NAME:IMAGE_TAG"}]' > imagedefinitions.json
      - sed -i -e "s|CONTAINER_NAME|$CONTAINER_NAME|g" imagedefinitions.json
      - sed -i -e "s|IMAGE_REPO_NAME|$IMAGE_REPO_NAME|g" imagedefinitions.json
      - sed -i -e "s|AWS_ACCOUNT_ID|$AWS_ACCOUNT_ID|g" imagedefinitions.json
      - sed -i -e "s|AWS_REGION|$AWS_REGION|g" imagedefinitions.json
      - sed -i -e "s|IMAGE_TAG|$IMAGE_TAG|g" imagedefinitions.json
      - cat imagedefinitions.json
  post_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

artifacts:
  files:
    - imagedefinitions.json
