version: 0.2

phases:
  build:
    commands:
      - npm install
      - npx serverless package
      - mv .serverless/cloudformation-template-update-stack.json packaged.json

artifacts:
  files:
    - packaged.json