version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
  nest:
    depends_on: [db]
    build: .
    command: sh -c "dockerize -wait tcp://db:3306 -timeout 15s -wait-retry-interval 3s npm run test"
