service:
  name: eventlab-v2

plugins:
  - serverless-plugin-typescript
#  - serverless-plugin-optimize
  - serverless-offline
  - serverless-plugin-canary-deployments

custom:
  serverless-offline:
    noPrependStageInUrl: true

package:
  include:
    - ormconfig.js

provider:
  name: aws
  runtime: nodejs12.x

functions:
  main: # The name of the lambda function
    # The module 'handler' is exported in the file 'src/lambda'
    handler: src/lambda.handler
    events:
      - httpApi: '*'
    deploymentSettings:
      type: AllAtOnce
      alias: Live